apiVersion: v1
kind: Service
metadata:
    name: "l3monitfk8s-8a10"
    labels:
        app: "l3monitfk8s-8a10"
spec:
    type: LoadBalancer
    ports:
    - port: 11000
      targetPort: 11000
      protocol: TCP
      name: http
    selector:
        app: "l3monitfk8s-8a10"